[package]
name = "lalrpop-demo"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"

[build-dependencies.lalrpop]
version = "0.19.1"
features = ["lexer"]
